# Generated by Django 3.0.5 on 2020-04-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0017_auto_20200104_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.Firm'),
        ),
    ]
